### ISSUE TITLE
Relationship to Celer State Guardian Network?

### ISSUE THREAD

**Issue by prototypo** [MultiMessageAggregation/multibridge#9]
What is the relationship between this project and https://github.com/celer-network/sgn-v2-contracts/tree/multibridge/contracts/message/apps/multibridge ? It looks like they share @xiaozhou as a dev, but are diverging? Thanks.

**Comment by 0xkydo** [comment]
Thanks for asking! The Celer team originally started and worked on this project within their own repository. However, since this project has now become more than just a Celer project, we thought it would be best to move it to a separate organization. The [old repo](https://github.com/celer-network/sgn-v2-contracts/tree/multibridge/contracts/message/apps/multibridge) is no longer being worked on.

Let us know if you have any other questions! If not, feel free to close the issue.

**Comment by prototypo** [comment]
Thanks, @0xkydo! That's super helpful.
